#!/bin/bash
GCC="/build/rpi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc"
# run the container as a user to simplify writing files outside the container
docker run --rm -it -v $(pwd):$(pwd) -w $(pwd) lispmeister/rpxp -U fix -u 1000 -G fix -g 1000  $GCC "$@"
