#!/bin/bash

# run the container as a user to simplify writing files outside the container
docker run --rm -it -v $(pwd):$(pwd) -w $(pwd) lispmeister/ponyc -U fix -u 1000 -G fix -g 1000 /usr/src/ponyc/build/release/ponyc "$@"
